modLoader="javafml"
loaderVersion="[4,)"
license="DSMSLv3.1 (DON'T SNATCH MA STUFF LISENSE v3.1)"

[[mods]]
modId="immortality_potion"
version="1.0.0"
displayName="Potion Of Immortality"
displayURL="https://github.com/Bagelman47"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Bagelman47"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.immortality_potion]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.immortality_potion]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration